apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: tr2-db
spec:
  memorySize: 100MB
  tlsMode: enabled
  modulesList:
  - name: search
    version: 2.4.8
  - name: ReJSON
    version: 2.0.8
