apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisbank-ui-deployment
spec:
  selector:
    matchLabels:
      app: redisbank-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: redisbank-ui
    spec:
      containers:
      - name: redisbank-ui
        image: <youracrname>.azurecr.io/redisbank-ui:latest
        imagePullPolicy: Always
        ports:
        - name: redisbank-ui
          containerPort: 8080
        env:
        - name: AM_URI
          value: "http://am.<region>.<example>.demo.redislabs.com"
        - name: PFM_URI
          value: "http://pfm.<region>.<example>.demo.redislabs.com"
        - name: TR_URI
          value: "http://tr.<region>.<example>.demo.redislabs.com"
        - name: STOMP_HOST
          value: "ui.<region>.<example>.demo.redislabs.com"
        - name: STOMP_PORT
          value: "80"
        - name: STOMP_PROTOCOL
          value: "ws"
        - name: SPRING_REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redb-eventbus
              key: service_name
        - name: SPRING_REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: redb-eventbus
              key: port
        - name: SPRING_PROFILES_ACTIVE
          value: "tls"

